
version: '3.7'

services:
  employee-hierarchy-hub:
    container_name: employee-hierarchy-hub                                                                                                                                                                                                                                                                                                     
    build:
      context: .
      dockerfile: Dockerfile.development
    command: npm run start:dev
    ports:
      - "4000:4000"
    volumes:
      - .:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    env_file:
      - .env
volumes:
  node_modules:

